#%RAML 1.0
title: august2

types:
  person:
    properties:
      name: string
      age: number
      email: string


/getPersons:
  get:
    body:
      application/json:
        type: person[]
        example:
          - {age : 10, name : fran, email: 'fran@losardo.com'}
          - {age: 20, name : pepe, email : 'fran@losardo.com'}