#%RAML 1.0
title: august

types:
  person:
    properties:
      name: string
      age: number


/getPersons:
  get:
    body:
      application/json:
        type: person[]
        example:
          - {age : 10, name : fran}
          - {age: }